# NumPy常用数据结构

## 数组创建

In [1]:
import numpy as np
arr1 = np.array([1, 23, 34, 5, 5, 6])

In [2]:
arr1

array([ 1, 23, 34,  5,  5,  6])

In [3]:
arr2 = np.array([1, 234, 5, 56, 7, 356, 343], dtype=float)

In [4]:
arr2

array([  1., 234.,   5.,  56.,   7., 356., 343.])

In [5]:
arr3 = np.array([[1, 234, 123, 4], [1, 234, 54, 5322], [123, 44, 31, 212]])

In [6]:
arr3

array([[   1,  234,  123,    4],
       [   1,  234,   54, 5322],
       [ 123,   44,   31,  212]])

In [7]:
np.arange(0,100,0.5)

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. , 10.5,
       11. , 11.5, 12. , 12.5, 13. , 13.5, 14. , 14.5, 15. , 15.5, 16. ,
       16.5, 17. , 17.5, 18. , 18.5, 19. , 19.5, 20. , 20.5, 21. , 21.5,
       22. , 22.5, 23. , 23.5, 24. , 24.5, 25. , 25.5, 26. , 26.5, 27. ,
       27.5, 28. , 28.5, 29. , 29.5, 30. , 30.5, 31. , 31.5, 32. , 32.5,
       33. , 33.5, 34. , 34.5, 35. , 35.5, 36. , 36.5, 37. , 37.5, 38. ,
       38.5, 39. , 39.5, 40. , 40.5, 41. , 41.5, 42. , 42.5, 43. , 43.5,
       44. , 44.5, 45. , 45.5, 46. , 46.5, 47. , 47.5, 48. , 48.5, 49. ,
       49.5, 50. , 50.5, 51. , 51.5, 52. , 52.5, 53. , 53.5, 54. , 54.5,
       55. , 55.5, 56. , 56.5, 57. , 57.5, 58. , 58.5, 59. , 59.5, 60. ,
       60.5, 61. , 61.5, 62. , 62.5, 63. , 63.5, 64. , 64.5, 65. , 65.5,
       66. , 66.5, 67. , 67.5, 68. , 68.5, 69. , 69.5, 70. , 70.5, 71. ,
       71.5, 72. , 72.5, 73. , 73.5, 74. , 74.5, 75

In [10]:
np.linspace(0,10,10,endpoint=True)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [11]:
np.zeros([3,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
np.ones([3,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
arr3 +1

array([[   2,  235,  124,    5],
       [   2,  235,   55, 5323],
       [ 124,   45,   32,  213]])

## 数组方法

In [15]:
arr3

array([[   1,  234,  123,    4],
       [   1,  234,   54, 5322],
       [ 123,   44,   31,  212]])

In [16]:
arr3.ndim

2

In [17]:
arr3.shape

(3, 4)

In [19]:
arr3.size

12

In [20]:
arr3.dtype

dtype('int32')

In [21]:
arr2[2]

5.0

In [22]:
arr2

array([  1., 234.,   5.,  56.,   7., 356., 343.])

In [23]:
arr3[2]

array([123,  44,  31, 212])

In [24]:
arr3[2, 1]

44

In [30]:
data = ((2, 34.3, 234, 32), (1, 23, 4453, 23), (3, 443, 211, 432.3))
arr4 = np.array(data)
arr4

array([[2.000e+00, 3.430e+01, 2.340e+02, 3.200e+01],
       [1.000e+00, 2.300e+01, 4.453e+03, 2.300e+01],
       [3.000e+00, 4.430e+02, 2.110e+02, 4.323e+02]])

## NumPy常用数据清洗函数

In [31]:
s = np.array([1,2,3,2,34,34,5,56,4,3,3,32,41,2,34,33])

In [32]:
np.sort(s)

array([ 1,  2,  2,  2,  3,  3,  3,  4,  5, 32, 33, 34, 34, 34, 41, 56])

In [33]:
sorted(s,reverse=True)

[56, 41, 34, 34, 34, 33, 32, 5, 4, 3, 3, 3, 2, 2, 2, 1]

In [60]:
arr1 = np.array([[0,1,3],[4,2,9],[4,5,9],[1,-3,4]])
arr1
type(arr1)

numpy.ndarray

In [37]:
np.sort(arr1,axis = 0) # 0代表沿着行的方向， 1代表沿着列的方向

array([[ 0, -3,  3],
       [ 1,  1,  4],
       [ 4,  2,  9],
       [ 4,  5,  9]])

In [38]:
np.sort(arr1,axis = 1)

array([[ 0,  1,  3],
       [ 2,  4,  9],
       [ 4,  5,  9],
       [-3,  1,  4]])

In [ ]:
s = np.array([1,2,3,4,3,1,2,2,4,6,7,2,4,8,4,5])

In [40]:
np.argsort(s)

array([ 0,  5,  1,  6,  7, 11,  2,  4,  3,  8, 12, 14, 15,  9, 10, 13],
      dtype=int64)

In [43]:
np.where(s>3,1,-1)# 满足条件的，赋值为3，不满足的赋值为-1，返回的数据长度和s一样

array([-1, -1, -1,  1, -1, -1, -1, -1,  1,  1,  1, -1,  1,  1,  1,  1])

In [44]:
np.extract(s>3,s)# 只输出满足条件的数据

array([4, 4, 6, 7, 4, 8, 4, 5])

# Pandas

## Pandas常用数据结构

In [45]:
import numpy as np
import pandas as pd 

D:\Program Files (x86)\anaconda\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
D:\Program Files (x86)\anaconda\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


### Series构造

In [46]:
# 构造序列
series1 = pd.Series([2.8,3.01,8.99,8.59,5.18])

In [47]:
series1

0    2.80
1    3.01
2    8.99
3    8.59
4    5.18
dtype: float64

In [54]:
series2 = pd.Series([2.8,3.01,8.99,8.59,5.18],index = ['a','b','c','d','e'],dtype=float,name ='这是一个series')

In [55]:
series2

a    2.80
b    3.01
c    8.99
d    8.59
e    5.18
Name: 这是一个series, dtype: float64

In [50]:
series3 = pd.Series({'北京':2.8,'上海':3.01,'广东':8.99,'江苏':8.59,'浙江':5.18})

In [51]:
series3

北京    2.80
上海    3.01
广东    8.99
江苏    8.59
浙江    5.18
dtype: float64

### series方法

In [52]:
series2.values

array([2.8 , 3.01, 8.99, 8.59, 5.18])

In [53]:
series3.index

Index(['北京', '上海', '广东', '江苏', '浙江'], dtype='object')

### Dataframe构造

In [57]:
# 构造数据框
#数据框其实就是一个二维表结构，是数据分析中，最常用的数据结构
list1 = [['张三',23,'男'],['李四',27,'女'],['王二',26,'女']]   #使用嵌套列表
df1 = pd.DataFrame(list1,columns=['姓名','年龄','性别'])

In [58]:
df1

姓名  年龄 性别
0  张三  23  男
1  李四  27  女
2  王二  26  女

In [59]:
type(df1)

pandas.core.frame.DataFrame

In [61]:
df2 = pd.DataFrame({'姓名':['张三','李四','王二'],'年龄':[23,27,26],'性别':['男','女','女']}) 
#使用字典,字典的键被当成列名

In [62]:
df2

姓名  年龄 性别
0  张三  23  男
1  李四  27  女
2  王二  26  女

In [65]:
array1 = np.array([['张三',23,'男'],['李四',27,'女'],['王二', 26,'女']]) 
#使用numpy
df3 = pd.DataFrame(array1,columns=['姓名','年龄','性别'],index = ['a','b','c'] )

In [66]:
array1

array([['张三', '23', '男'],
       ['李四', '27', '女'],
       ['王二', '26', '女']], dtype='<U2')

In [64]:
df3

姓名  年龄 性别
a  张三  23  男
b  李四  27  女
c  王二  26  女

### Dataframe方法

In [67]:
df2

姓名  年龄 性别
0  张三  23  男
1  李四  27  女
2  王二  26  女

In [69]:
df2.values

array([['张三', 23, '男'],
       ['李四', 27, '女'],
       ['王二', 26, '女']], dtype=object)

In [70]:
df2.index

RangeIndex(start=0, stop=3, step=1)

In [71]:
df2.columns

Index(['姓名', '年龄', '性别'], dtype='object')

In [73]:
df2.dtypes

姓名    object
年龄     int64
性别    object
dtype: object

In [74]:
df2.ndim

2

In [75]:
df2.size

9

In [76]:
df2.shape

(3, 3)